# Generated by Django 5.1.6 on 2025-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('yers', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
