# Generated by Django 5.1.6 on 2025-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_delete_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
